/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LABDANIALEISA;

import javax.swing.ImageIcon;
import javax.swing.JFrame;

public class App {

    public static void main(String[] args) {
        Game game = new Game();
        game.startThread();
        
        
        
         
        
    }
}
