/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LABDANIALEISA;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAMain() {
        
        assertNotNull(new App());
    }
}
